apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatapp-server
spec:
  selector:
    matchLabels:
      app: chatapp-server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
